#!/bin/bash
# uzblicious
# (c) 2012 magnific0 (http://www.github.com/magnific0)
# released under GPLv3
usage()
{
cat << EOF
usage: $0 [-hcsn] [-b [<browse_source>]] [-a [<url>]]

This script will control bookmarking and history for UZBL

OPTIONS:
   -h      Show this message
   -b      Browse source (bookmarks by default)
   -n      New window
   -s      Sync bookmarks with delicious
   -a      Add new bookmarks (can only be spawned from within UZBL)
   -c      Clean history

EXAMPLES:
uzblicious -b history -n
uzblicious -a http://www.google.com

EOF
}

[ -z "$XDG_DATA_HOME" ] && del_browser_dir="$HOME"/.local/share/uzbl || del_browser_dir="$XDG_DATA_HOME"/uzbl
[ -z "$XDG_CONFIG_HOME" ] && del_browser_cdir="$HOME"/.config/uzbl || del_browser_cdir="$XDG_CONFIG_HOME"/uzbl 

log()
{
    dt=$(date)
    msg="${1}"
    echo "$dt - $msg">>$del_browser_dir/uzblicious.log
}

freshrun(){
    cp /usr/share/uzbl/examples/config/uzblicious.conf.example $del_browser_cdir/uzblicious.conf
    touch $del_browser_dir/bookmarks
    touch $del_browser_dir/bookmarks.ver
    touch $del_browser_dir/bookmarks.count
    touch $del_browser_dir/uzblicious.log
    touch $del_browser_dir/history

    # only if it is NOT spawned from within uzbl give user oppurtunity to edit the file
    if [ -z $UZBL_URI ]; then
	read -p "New configuration file copied, would you like to edit it? (Y/n):"
	if [ "$REPLY" == "y" ] || [ "$REPLY" == "Y" ] || [ -z $REPLY ]; then
	    vi $del_browser_cdir/uzblicious.conf
	else
	    echo "You still need to setup your delicious account, edit:"
	    echo "$del_browser_cdir/uzblicious.conf"
	    echo "using your favourite editor."
	fi
    fi
    log "INSTALL fresh installation"
}

clean()
{
    cat $del_browser_dir/history >  $del_browser_dir/history.bak
    tac $del_browser_dir/history.bak | awk ' !x[$0]++' > $del_browser_dir/history.rev
    tac $del_browser_dir/history.rev > $del_browser_dir/history
    rm -f $del_browser_dir/history.bak
    rm -f $del_browser_dir/history.rev
    exit
}

sync()
{

    log "START fetching bookmarks from delicious. User: $user"

    resp=$(curl -s "https://$user:$passwd@api.del.icio.us/v1/posts/update") 
    
    if echo "$resp" | grep "<result code=\"access denied\"/>" >/dev/null; then
        echo "Error: Access denied."
        log "ERROR while fetching bookmarks from delicious. (Access denied)"
        exit
    fi    
    
    if [ -z "$resp" ]; then
        log "ERROR while fetching bookmarks from delicious. (Internet or host seems down)"
        exit
    fi 

    datemodified=$(echo $resp | sed 's/"/\n/g' | grep -A 1 time | tail -1)
    
    cacheversion=$(cat $del_browser_dir/bookmarks.ver)

    if [ "$datemodified" == "$cacheversion" ]; then
	log "DONE bookmarks cache is uptodate."
	exit
    fi

    resp=$(curl -s "https://$user:$passwd@api.del.icio.us/v1/posts/all")

    echo "$resp" | sed 's/<post/\n<post/g' | sed 's/\/>/\/>\n/g' | grep href | sed 's/<[^>]*hash\="\([^"]*\)"[^>]*href\="\([^"]*\)"[^>]*tag\="\([^"]*\)"[^>]*\/>/\1 \2 \3/g' > $del_browser_dir/bookmarks
    
    echo "$datemodified" > $del_browser_dir/bookmarks.ver

    log "DONE fetching bookmarks from delicious."
    exit
}

add()
{
    url=$UZBL_URI
    title=$UZBL_TITLE

    resp=$(curl "https://$user:$passwd@api.del.icio.us/v1/posts/suggest?url=$url" -s)

    if echo "$resp" | grep "<result code=\"access denied\"/>" >/dev/null; then 
	echo "Error: Access denied."
	log "ERROR while fetching bookmarks from delicious. (Access denied)"
	exit
    fi

    recoms=`echo "$resp" | sed 's/</\n</g' | sed 's/\/>/\/>\n/g' | grep tag | sed 's/<[^>]*tag\="\([^"]*\)"[^>]*\/>/\1/g'`

    prompt=1

    while [  $prompt -eq 1 ]; do
	tag=$(echo "$recoms" | dmenu -p "Tags for $url:" $dmenu_args_colors)
  
	if [ ${#tag} -lt 1 ]; then
	    prompt=0
	else
	    tags="$tags$tag, "
	    recoms=$(echo "$recoms"|sed "/$tag/d")
	fi
    done

    log "START adding new bookmark: $url (tags: $tags, title: $title)"
    
    if $abort_on_zero_tags && [ -z "$tags" ]; then
	log "ERROR no tags were supply aborting."
    else
        # add bookmark to delicious and sync
	response=$(curl -s "https://$user:$passwd@api.del.icio.us/v1/posts/add" -d "url=$url&description=$title&tags=$tags")
	if echo "$response" | grep "code=\"done\"" >/dev/null; then
	    log "DONE adding new bookmark"
	    sync
	else
	    log "ERROR occured adding '$url' to delicious account ($user): $response"
	fi
    fi
    exit
}

# some defaults for browsing
BRSOURCE=bookmarks
NEWWINDOW=false

# read configuration
# if no configuration file was found, make one
[ -f $del_browser_cdir/uzblicious.conf ] || freshrun
source $del_browser_cdir/uzblicious.conf

while getopts hab:ncs o
do	case "$o" in
	h) 
	    usage
	    exit;;
	a)
	    if [ ! -z $2 ]; then
		UZBL_URI="$2"
		UZBL_TITLE=`curl -L --silent $UZBL_URI | sed -n -e 'H;${x;s!.*<head[^>]*>\(.*\)</head>.*!\1!;tnext};b;:next;s!.*<title>\(.*\)</title>.*!\1!p'`
	    fi
	    add
	    ;;
	b)  
	    BRSOURCE="$OPTARG"
	    ;;
	s)  
	    sync
	    ;;
	n)  
	    NEWWINDOW=true;;
	c)
	    clean
	    ;;
	[?])
	    usage
	    exit;;
	esac
done

if [ $BRSOURCE == "history" ]; then
    # get choice back from history
    URL=$(sort -r $del_browser_dir/history | dmenu ${dmenu_args_colors} ${dmenu_args_browse} | awk '{print $3}')
else
    # get the choice back from dmenu and extract very first "word"
    # urls with joining entry in bookmarks.count
    URLS_J=$(join <(sort $del_browser_dir/bookmarks.count) <(sort $del_browser_dir/bookmarks) | sort -k2 -nr)
    # urls without joining entry
    URLS_U=$(join -v 2 <(sort $del_browser_dir/bookmarks.count) <(sort $del_browser_dir/bookmarks) | awk '{printf $1" 0 "; for (i=2; i<=NF; i++) printf "%s ",$i; printf "\n"}')
    # full list
    URLS_F=$(echo -e "$URLS_J\n$URLS_U")
    # short list (excluding hashes and counts)
    URLS_S=$(echo "$URLS_F" | awk '{for (i=3; i<=NF; i++) printf "%s ",$i; printf "\n"}')
    URL=$(echo "$URLS_S" | dmenu ${dmenu_args_colors} ${dmenu_args_browse})
    URL_F=$(echo "$URLS_F" | grep -m 1 "$URL")
    # if the user entered nothing, perhaps dmenu was aborted with ESC or empty entry with Shift-Enter
    if [ -z "$URL" ]; then
	exit
    fi	

    # URL regex 
    # http://www.example.com www.example.com example.com are all allowed
    URLRGX='^((([hH][tT][tT][pP][sS]?|[fF][tT][pP])\:\/\/)?([\w\.\-]+(\:[\w\.\&%\$\-]+)*@)?((([^\s\(\)\<\>\\\"\.\[\]\,@;:]+)(\.[^\s\(\)\<\>\\\"\.\[\]\,@;:]+)*(\.[a-zA-Z]{2,4}))|((([01]?\d{1,2}|2[0-4]\d|25[0-5])\.){3}([01]?\d{1,2}|2[0-4]\d|25[0-5])))(\b\:(6553[0-5]|655[0-2]\d|65[0-4]\d{2}|6[0-4]\d{3}|[1-5]\d{4}|[1-9]\d{0,3}|0)\b)?((\/[^\/][\w\.\,\?'\''\\\/\+&%\$#\=~_\-@]*)*[^\.\,\?\"'\''\(\)\[\]!;<>{}\s\x7F-\xFF])?)$'
    
    # full line match of chosen url to urls, to see if an entry was selected
    if $(echo "$URLS_S" | grep -x "$URL" > /dev/null); then
	# increment count on url
	CHASH=$(echo $URL_F | awk '{print $1}') # hash
	COUNT=$(echo $URL_F | awk '{print $2}') # count number
	# if count is not a number hash was never in the bookmarks_count file, meaning 0 visits
	URL=$(echo $URL | awk '{print $1}') 
	COUNT=$(expr $COUNT + 1)
	sed '/'"$CHASH"'/d' $del_browser_dir/bookmarks.count > $del_browser_dir/bookmarks.count.tmp
	echo "$CHASH $COUNT" >> $del_browser_dir/bookmarks.count.tmp
	mv -f $del_browser_dir/bookmarks.count.tmp $del_browser_dir/bookmarks.count
    # if not a bookmark and is not an URL then treat as search string
    elif echo "$URL" | grep -Pve $URLRGX >/dev/null; then 
        # match the specified search engine
	for i in $(eval echo {0..$(expr ${#search_handlers[@]} - 1)..2}); do
	    if echo $URL | awk '{print $1}' | egrep ${search_handlers[i]} >/dev/null; then
	        #get the search url from array and extract keywords
		ARG=$(echo $URL | awk -F: '{for (i=2; i<=NF; i++) print $i}')
		URL=${search_handlers[$(expr $i + 1)]}
		break
	    fi 
	done
        # none found: take the first (default) search engine
	if [ -z $ARG ]; then
	    ARG=$URL 
	    URL=${search_handlers[1]}	    
	fi
        # function to encode the keywords
	rawurlencode() {
	    local string="${1}"
	    local strlen=${#string}
	    local encoded=""

	    for (( pos=0 ; pos<strlen ; pos++ )); do
		c=${string:$pos:1}
		case "$c" in
		    [-_.~a-zA-Z0-9] ) 
			o="${c}" 
			;;
		    * ) 
			printf -v o '%%%02x' "'$c"
		esac
		encoded+="${o}"
	    done
	    ARG="${encoded}"
	}

            # encode the keywords and create url
	rawurlencode "$ARG"
	URL=$(echo $URL | sed "s/%s/$ARG/g")
    fi
fi



# if a URL is set
if [ ! -z $URL ]; then
  # see if a new window is required
  if $NEWWINDOW || [ -z $UZBL_SOCKET ]; then
    eval "uzbl-browser \"$URL\" 2> /dev/null &"
  else    
    echo "uri $URL" | socat - "unix-connect:$UZBL_SOCKET"
  fi
else
    echo "no proper url was returned"
    usage
fi

exit
